disableKinds = ["taxonomy","taxonomyTerm"]

title = 'MinID'

baseURL = ''
languageCode = 'nb'
theme = 'digdir-hugo-theme'

defaultContentLanguage = 'no'

enableRobotsTXT = true

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

[imaging]
  anchor = 'Smart'
  hint = 'photo'
  quality = 80
  resampleFilter = 'MitchellNetravali'

[languages]
  [languages.no]
    languageName = "Norsk"
    weight = 1
    other = "Norsk"
  [languages.en]
    languageName = "English"
    weight = 2
    other = "English"

[params]
    logo = '/images/logo-minid.svg'
    global_keywords = ['digdir', 'minid', 'elektronsik', 'identitet', 'offentlig', 'digitaliseringsdirektoratet']